// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.API.Infrastructure;

namespace Product.API.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20200520183128_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Product.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Poulet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Curry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tandori"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Boun"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pokeball"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pokeball"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
